### ISSUE TITLE
Is there a way to do matix * vector multiplication

### ISSUE THREAD

**Issue by CAMOBAP** [stackgl/gl-mat4#12]
I see possibility to calculate `M * M` but looks like no API to dod `M * V` calculation

**Comment by rreusser** [comment]
Since the result is, say, a vec3, those methods are in the repo of the type they'd be expected to return. See, for example: https://github.com/stackgl/gl-vec3#transformmat3outvec3-avec3-mmat3

**Comment by CAMOBAP** [comment]
Thanks @rreusser exactly what I looked for
